replicaCount: 1

image:
  repository: x-ui
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  host: momofamily.tplinkdns.com
  path: /
  pathType: Prefix
  tls:
    - secretName: x-ui-tls
      hosts:
        - momofamily.tplinkdns.com

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

# Number of old ReplicaSets to retain
revisionHistoryLimit: 3

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
